"""Workshop Props + Product Staging pass for the approved Puerto Nuevo scene.

Run on the approved file with Blender 5.2 LTS:
  blender --background blender/puerto-nuevo-workshop.blend \
    --python blender/scripts/build_workshop_props.py

No external assets are used. All geometry and materials are original and
procedurally generated by this script.
"""

from pathlib import Path
import math

import bpy
from mathutils import Vector


ROOT = Path(__file__).resolve().parents[2]
BLEND_PATH = ROOT / "blender" / "puerto-nuevo-workshop.blend"
RENDER_DIR = ROOT / "blender" / "renders"
TARGET_PATH = ROOT / "art-direction" / "puerto-nuevo-blender-art-target-v2.png"

MAIN_RENDER = RENDER_DIR / "workshop-props-preview.png"
BENCH_RENDER = RENDER_DIR / "workbench-staging-closeup.png"
LEFT_RENDER = RENDER_DIR / "eyewear-left-closeup.png"
RIGHT_RENDER = RENDER_DIR / "eyewear-right-closeup.png"
HERO_RENDER = RENDER_DIR / "eyewear-hero-closeup.png"
TURNTABLE_RENDER = RENDER_DIR / "turntable-closeup.png"
COMPARISON_RENDER = RENDER_DIR / "camera-comparison-props.png"
MACHINE_LEFT_RENDER = RENDER_DIR / "machinery-left-closeup.png"
MACHINE_RIGHT_RENDER = RENDER_DIR / "machinery-right-closeup.png"
DIAGNOSTIC_RENDER = RENDER_DIR / "materials-lighting-diagnostic.png"

COUNTER_TOP_Z = 1.09


def remove_old_pass():
    for obj in list(bpy.data.objects):
        if obj.name.startswith("PN_TaskLamp_Practical") or obj.name.startswith("PN_ShelfLight_"):
            bpy.data.objects.remove(obj,do_unlink=True)
    for cname in ("PN_Eyewear_Products", "PN_Workshop_Machinery", "PN_Hand_Tools",
                  "PN_Turntable", "PN_Product_Staging", "PN_Props_Cameras"):
        col = bpy.data.collections.get(cname)
        if col:
            for obj in list(col.all_objects):
                bpy.data.objects.remove(obj, do_unlink=True)
            bpy.data.collections.remove(col)
    for cname in ("PN_Props_Lighting",):
        col = bpy.data.collections.get(cname)
        if col:
            for obj in list(col.all_objects):
                bpy.data.objects.remove(obj, do_unlink=True)
            bpy.data.collections.remove(col)
    for mname in [m.name for m in bpy.data.materials if m.name.startswith("MAT_Prop_") or m.name.startswith("MAT_Acetate_")]:
        bpy.data.materials.remove(bpy.data.materials[mname])


def collection(name):
    col = bpy.data.collections.new(name)
    bpy.context.scene.collection.children.link(col)
    return col


def mat(name, color, rough=0.5, metallic=0.0, transmission=0.0, alpha=1.0):
    m = bpy.data.materials.new(name)
    m.diffuse_color = (*color, alpha)
    m.use_nodes = True
    bsdf = m.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = (*color, 1)
    bsdf.inputs["Roughness"].default_value = rough
    bsdf.inputs["Metallic"].default_value = metallic
    bsdf.inputs["IOR"].default_value = 1.46
    if transmission:
        bsdf.inputs["Transmission Weight"].default_value = transmission
    if alpha < 1:
        bsdf.inputs["Alpha"].default_value = alpha
    return m


def box(name, loc, dims, material, col, bevel=0.01, parent=None):
    bpy.ops.mesh.primitive_cube_add(location=loc)
    o = bpy.context.object
    o.name = name
    o.dimensions = dims
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    if bevel:
        mod = o.modifiers.new("EdgeWear", "BEVEL")
        mod.width = bevel
        mod.segments = 2
    o.data.materials.append(material)
    move(o, col)
    if parent:
        o.parent = parent
        o.matrix_parent_inverse = parent.matrix_world.inverted()
    return o


def cylinder(name, loc, radius, depth, material, col, vertices=24, rotation=None, parent=None):
    bpy.ops.mesh.primitive_cylinder_add(vertices=vertices, radius=radius, depth=depth, location=loc,
                                       rotation=rotation or (0,0,0))
    o = bpy.context.object
    o.name = name
    o.data.materials.append(material)
    move(o, col)
    if parent:
        o.parent = parent
        o.matrix_parent_inverse = parent.matrix_world.inverted()
    return o


def move(obj, col):
    for c in list(obj.users_collection):
        c.objects.unlink(obj)
    col.objects.link(obj)


def tube(name, points, radius, material, col, cyclic=False, parent=None, resolution=1):
    curve = bpy.data.curves.new(name+"_Curve", "CURVE")
    curve.dimensions = "3D"
    curve.resolution_u = resolution
    curve.bevel_depth = radius
    curve.bevel_resolution = 2
    spl = curve.splines.new("POLY")
    spl.points.add(len(points)-1)
    for p, co in zip(spl.points, points):
        p.co = (*co,1)
    spl.use_cyclic_u = cyclic
    o = bpy.data.objects.new(name, curve)
    col.objects.link(o)
    o.data.materials.append(material)
    if parent:
        o.parent = parent
        o.matrix_parent_inverse = parent.matrix_world.inverted()
    return o


def rounded_rect_points(cx, cz, width, height, radius, segments=5):
    pts=[]
    corners=((cx+width/2-radius,cz+height/2-radius,0),
             (cx-width/2+radius,cz+height/2-radius,1),
             (cx-width/2+radius,cz-height/2+radius,2),
             (cx+width/2-radius,cz-height/2+radius,3))
    ranges=((0,math.pi/2),(math.pi/2,math.pi),(math.pi,3*math.pi/2),(3*math.pi/2,math.tau))
    for (x,z,_),(a0,a1) in zip(corners,ranges):
        for i in range(segments):
            a=a0+(a1-a0)*i/(segments-1)
            pts.append((x+radius*math.cos(a),z+radius*math.sin(a)))
    return pts


def rounded_ring(name, cx, width, height, corner, rim, depth, material, col, root):
    outer=rounded_rect_points(cx,0,width,height,corner,6)
    inner=rounded_rect_points(cx,0,width-2*rim,height-2*rim,max(0.018,corner-rim),6)
    n=len(outer); verts=[]
    for y in (-depth/2,depth/2):
        verts += [(x,y,z) for x,z in outer] + [(x,y,z) for x,z in inner]
    faces=[]
    # Front/back annular faces and outer/inner depth walls.
    for i in range(n):
        j=(i+1)%n
        faces += [(i,j,n+j,n+i), (2*n+i,3*n+i,3*n+j,2*n+j),
                  (i,2*n+i,2*n+j,j), (n+i,n+j,3*n+j,3*n+i)]
    mesh=bpy.data.meshes.new(name+"_Mesh"); mesh.from_pydata(verts,[],faces); mesh.update()
    obj=bpy.data.objects.new(name,mesh); col.objects.link(obj); obj.data.materials.append(material); obj.parent=root
    bevel=obj.modifiers.new("AcetateEdgeBevel","BEVEL"); bevel.width=0.006; bevel.segments=2
    return obj


def rounded_lens(name,cx,width,height,corner,material,col,root):
    pts=rounded_rect_points(cx,0,width,height,corner,6)
    verts=[(x,0.018,z) for x,z in pts]
    mesh=bpy.data.meshes.new(name+"_Mesh"); mesh.from_pydata(verts,[],[tuple(range(len(verts)))]); mesh.update()
    obj=bpy.data.objects.new(name,mesh); col.objects.link(obj); obj.data.materials.append(material); obj.parent=root
    solid=obj.modifiers.new("LensThickness","SOLIDIFY"); solid.thickness=0.006
    bevel=obj.modifiers.new("LensEdge","BEVEL"); bevel.width=0.003; bevel.segments=2
    return obj


def create_eyewear(name, location, acetate, clear, col, style=0, scale=1.0):
    root = bpy.data.objects.new(name, None)
    root.empty_display_type = "CUBE"
    root.empty_display_size = 0.12
    root.location = location
    root["product_id"] = name
    root["raycast_root"] = True
    root["future_animation_root"] = True
    col.objects.link(root)
    width=(0.285+0.012*(style%3))*scale
    height=(0.205+0.010*((style+1)%3))*scale
    center=(0.176+0.008*(style%2))*scale
    corner=(0.052+0.006*(style%3))*scale
    rim=(0.030+0.003*((style+1)%3))*scale
    depth=(0.040+0.004*(style%2))*scale
    for side,cx in (("L",-center),("R",center)):
        rounded_ring(f"{name}_Front_{side}",cx,width,height,corner,rim,depth,acetate,col,root)
        rounded_lens(f"{name}_Lens_{side}",cx,width-2*rim-0.008,height-2*rim-0.008,
                     max(0.015,corner-rim),clear,col,root)
        # Recognizable hinge block at the outer corner.
        hx=cx+(-1 if side=="L" else 1)*(width/2-0.006)
        h=box(f"{name}_Hinge_{side}",(location[0]+hx,location[1]-0.004,location[2]+0.006),
              (0.025,0.052,0.052),bpy.data.materials["MAT_Prop_AgedBrass"],col,0.005,root)
    bridge_z=0.018+0.008*(style%2)
    bridge_gap=2*center-width
    box(f"{name}_Bridge",(location[0],location[1],location[2]+bridge_z),
        (bridge_gap+0.045,depth,0.045),acetate,col,0.010,root)
    # Patillas recede onto the shelf instead of reading as flat whiskers.
    for side,sgn in (("L",-1),("R",1)):
        x=sgn*(center+width/2)
        tube(f"{name}_Temple_{side}",[(x,0,0.005),(x+sgn*0.09,0.08,-0.015),(x+sgn*0.12,0.26,-0.045)],
             0.010*scale,acetate,col,False,root)
    return root


def create_materials():
    materials={
        "steel":mat("MAT_Prop_BlackenedSteel",(0.025,0.022,0.018),0.38,0.82),
        "steel2":mat("MAT_Prop_MachineGreen",(0.045,0.095,0.070),0.55,0.65),
        "brass":mat("MAT_Prop_AgedBrass",(0.24,0.13,0.035),0.42,0.82),
        "wood":mat("MAT_Prop_DarkWood",(0.07,0.020,0.006),0.50),
        "rubber":mat("MAT_Prop_Rubber",(0.012,0.012,0.011),0.78),
        "cloth":mat("MAT_Prop_Cloth",(0.24,0.19,0.13),0.92),
        "ceramic":mat("MAT_Prop_Ceramic",(0.30,0.27,0.21),0.58),
        "glass":mat("MAT_Prop_ClearGlass",(0.72,0.70,0.62),0.16,0,0.35,0.30),
        "vinyl":mat("MAT_Prop_Vinyl",(0.008,0.008,0.007),0.28),
        "amber":mat("MAT_Acetate_Amber",(0.32,0.105,0.018),0.38,0,0.10),
        "tortoise":mat("MAT_Acetate_Tortoise",(0.105,0.026,0.008),0.42),
        "smoke":mat("MAT_Acetate_Smoke",(0.075,0.065,0.055),0.34,0,0.10),
        "warmblack":mat("MAT_Acetate_WarmBlack",(0.012,0.009,0.007),0.35),
        "crystal":mat("MAT_Acetate_Crystal",(0.52,0.38,0.22),0.28,0,0.28,0.65),
        "lens":mat("MAT_Prop_NeutralLens",(0.46,0.45,0.40),0.18,0,0.45,0.28),
        "acetate_sheet":mat("MAT_Prop_AcetateSheet",(0.30,0.08,0.025),0.52),
    }
    return materials


def stage_eyewear(m, col, staging):
    positions=[]
    zs=(1.62,2.16,2.70,3.24)
    for i,z in enumerate(zs,1):
        positions.append((f"PN_Eyewear_{i:02d}",(-2.65,1.03,z),i-1))
    for j,z in enumerate(zs,5):
        positions.append((f"PN_Eyewear_{j:02d}",(2.65,1.03,z),j-1))
    acetate_cycle=(m["warmblack"],m["tortoise"],m["smoke"],m["amber"],
                   m["warmblack"],m["tortoise"],m["crystal"],m["amber"])
    roots=[]
    for (name,pos,style),acetate in zip(positions,acetate_cycle):
        roots.append(create_eyewear(name,pos,acetate,m["lens"],col,style,0.95))
    # Handcrafted center plinth and the ninth hero product.
    box("PN_HeroDisplay_Base",(0,0.50,1.145),(1.05,0.40,0.11),m["wood"],staging,0.025)
    box("PN_HeroDisplay_Riser",(0,0.50,1.225),(0.72,0.24,0.055),m["cloth"],staging,0.018)
    hero=create_eyewear("PN_Eyewear_09",(0,0.26,1.38),m["warmblack"],m["lens"],col,8,1.12)
    roots.append(hero)
    return roots


def editorial_plates_and_shelf_lights(m, staging, light_col):
    zs=(1.62,2.16,2.70,3.24)
    entries=[]
    for i,z in enumerate(zs,1): entries.append((i,-3.30,1.015,z))
    for i,z in enumerate(zs,5): entries.append((i,2.00,1.015,z))
    entries.append((9,-0.55,0.26,1.38))
    for number,x,y,z in entries:
        cylinder(f"PN_EditorialPlate_{number:02d}",(x,y,z),0.105,0.018,m["brass"],staging,32,
                 rotation=(math.pi/2,0,0))
        bpy.ops.object.text_add(location=(x,y-0.014,z),rotation=(math.pi/2,0,0))
        txt=bpy.context.object; txt.name=f"PN_EditorialNumber_{number:02d}"; txt.data.body=f"{number:02d}"
        txt.data.align_x="CENTER"; txt.data.align_y="CENTER"; txt.data.size=0.075; txt.data.extrude=0.002
        txt.data.materials.append(m["cloth"]); move(txt,staging)
    for side,x in (("L",-2.65),("R",2.65)):
        for level,z in enumerate((1.48,2.02,2.56,3.10),1):
            data=bpy.data.lights.new(f"PN_ShelfLight_{side}_{level:02d}_Data","POINT")
            data.energy=7.5; data.color=(1.0,0.69,0.42); data.shadow_soft_size=0.20
            light=bpy.data.objects.new(f"PN_ShelfLight_{side}_{level:02d}",data)
            light.location=(x,1.10,z+0.03); light_col.objects.link(light)


def refine_approved_wood():
    names=("MAT_Walnut_Provisional","MAT_Walnut_Dark","MAT_Walnut_Drawer_A",
           "MAT_Walnut_Drawer_B","MAT_Walnut_Frame")
    for name in names:
        material=bpy.data.materials.get(name)
        if not material or not material.use_nodes: continue
        nodes=material.node_tree.nodes; links=material.node_tree.links
        bsdf=nodes.get("Principled BSDF")
        if not bsdf: continue
        socket=bsdf.inputs["Base Color"]
        if socket.links:
            old=socket.links[0]; source=old.from_socket; links.remove(old)
            hue=nodes.new("ShaderNodeHueSaturation"); hue.inputs["Saturation"].default_value=0.62; hue.inputs["Value"].default_value=0.76
            links.new(source,hue.inputs["Color"]); links.new(hue.outputs["Color"],socket)
        for node in nodes:
            if node.bl_idname=="ShaderNodeMapRange":
                node.inputs["To Min"].default_value=max(0.46,node.inputs["To Min"].default_value)
                node.inputs["To Max"].default_value=max(0.64,node.inputs["To Max"].default_value)


def drill_press(m,col):
    p="PN_Machine_DrillPress"
    box(p+"_Base",(1.45,0.66,1.15),(0.48,0.38,0.12),m["steel2"],col,0.035)
    cylinder(p+"_Column",(1.55,0.76,1.78),0.055,1.18,m["steel"],col,24)
    box(p+"_Head",(1.49,0.62,2.18),(0.40,0.32,0.42),m["steel2"],col,0.055)
    cylinder(p+"_Chuck",(1.47,0.47,1.92),0.055,0.22,m["steel"],col,20)
    cylinder(p+"_Bit",(1.47,0.47,1.72),0.010,0.28,m["steel"],col,12)
    box(p+"_Table",(1.45,0.55,1.48),(0.38,0.32,0.06),m["steel"],col,0.02)
    for a in (-0.35,0,0.35):
        tube(p+f"_FeedHandle_{a:+.2f}",[(1.69,0.54,2.12),(1.69+0.18*math.cos(a),0.54,2.12+0.18*math.sin(a))],0.014,m["steel"],col)


def buffer(m,col):
    p="PN_Machine_Buffer"
    box(p+"_Base",(2.65,0.66,1.145),(0.54,0.34,0.10),m["steel2"],col,0.025)
    cylinder(p+"_Motor",(2.65,0.66,1.39),0.16,0.42,m["steel2"],col,24,rotation=(0,math.pi/2,0))
    cylinder(p+"_Wheel_L",(2.35,0.66,1.39),0.22,0.08,m["cloth"],col,28,rotation=(0,math.pi/2,0))
    cylinder(p+"_Wheel_R",(2.95,0.66,1.39),0.20,0.08,m["cloth"],col,28,rotation=(0,math.pi/2,0))


def sander(m,col):
    p="PN_Machine_SpindleSander"
    box(p+"_Base",(3.42,0.64,1.15),(0.46,0.38,0.12),m["steel2"],col,0.025)
    box(p+"_Table",(3.42,0.58,1.32),(0.52,0.42,0.08),m["steel"],col,0.018)
    cylinder(p+"_Spindle",(3.42,0.54,1.52),0.065,0.38,m["rubber"],col,24)


def vise_and_heater(m,col):
    p="PN_Machine_Vise"
    box(p+"_Base",(-1.72,0.70,1.16),(0.42,0.32,0.14),m["steel2"],col,0.025)
    box(p+"_JawFixed",(-1.82,0.54,1.34),(0.18,0.10,0.28),m["steel"],col,0.015)
    box(p+"_JawMoving",(-1.58,0.54,1.34),(0.18,0.10,0.28),m["steel"],col,0.015)
    tube(p+"_Handle",[(-1.50,0.47,1.18),(-1.20,0.47,1.18)],0.018,m["steel"],col)
    h="PN_Machine_FrameHeater"
    cylinder(h+"_Bowl",(-2.25,0.66,1.25),0.24,0.24,m["ceramic"],col,32)
    cylinder(h+"_Rim",(-2.25,0.66,1.38),0.255,0.035,m["brass"],col,32)
    box(h+"_Control",(-2.25,0.42,1.18),(0.20,0.08,0.10),m["steel"],col,0.01)


def machinery_details(m,col):
    # Functional controls, fasteners and power cables break up the primitive silhouettes.
    for i,z in enumerate((2.10,2.22),1):
        cylinder(f"PN_DrillPress_Control_{i:02d}",(1.26,0.43,z),0.036,0.045,m["brass"],col,18,
                 rotation=(math.pi/2,0,0))
    for i,x in enumerate((1.28,1.62),1):
        cylinder(f"PN_DrillPress_BaseBolt_{i:02d}",(x,0.48,1.22),0.018,0.025,m["brass"],col,14)
    tube("PN_DrillPress_PowerCable",[(1.60,0.84,1.95),(1.82,0.94,1.50),(1.96,0.90,1.10)],0.010,m["rubber"],col)
    cylinder("PN_Buffer_EndCap",(2.65,0.45,1.39),0.12,0.05,m["brass"],col,24,rotation=(math.pi/2,0,0))
    for x in (2.45,2.85):
        cylinder(f"PN_Buffer_Foot_{x:.2f}",(x,0.62,1.105),0.035,0.035,m["rubber"],col,16)
    cylinder("PN_Sander_AdjustKnob",(3.62,0.42,1.25),0.045,0.05,m["brass"],col,18,rotation=(math.pi/2,0,0))
    tube("PN_Sander_PowerCable",[(3.55,0.82,1.20),(3.72,0.92,1.15),(3.78,0.82,1.10)],0.010,m["rubber"],col)


def turntable(m,col):
    root=bpy.data.objects.new("PN_Turntable_Root",None)
    root.empty_display_type="CUBE"; root.empty_display_size=0.18; root.location=(-3.30,0.62,1.09)
    root["animatable_prop"]=True
    col.objects.link(root)
    box("PN_Turntable_Base",(-3.30,0.62,1.19),(0.98,0.62,0.20),m["wood"],col,0.035,root)
    cylinder("PN_Turntable_Platter",(-3.30,0.58,1.34),0.34,0.055,m["steel"],col,48,parent=root)
    record=cylinder("PN_Turntable_Record",(-3.30,0.58,1.375),0.30,0.018,m["vinyl"],col,48,parent=root)
    record["animation_axis"]="Z"; record["clip_name"]="spin"
    cylinder("PN_Turntable_Label",(-3.30,0.58,1.387),0.075,0.006,m["amber"],col,32,parent=root)
    arm_root=bpy.data.objects.new("PN_Turntable_Tonearm_Root",None); arm_root.location=(-2.94,0.48,1.39); col.objects.link(arm_root); arm_root.parent=root; arm_root.matrix_parent_inverse=root.matrix_world.inverted()
    cylinder("PN_Turntable_TonearmPivot",(-2.94,0.48,1.42),0.055,0.08,m["brass"],col,24,parent=arm_root)
    tube("PN_Turntable_Tonearm",[(-2.94,0.48,1.46),(-3.10,0.40,1.49),(-3.23,0.40,1.44)],0.014,m["brass"],col,parent=arm_root)
    box("PN_Turntable_Cartridge",(-3.23,0.40,1.43),(0.08,0.05,0.035),m["steel"],col,0.006,arm_root)
    for i,x in enumerate((-3.68,-3.58),1):
        cylinder(f"PN_Turntable_Control_{i:02d}",(x,0.38,1.33),0.035,0.035,m["brass"],col,20,parent=root)


def hand_tools(m,col):
    # Left adjustment cluster: files, pliers and screwdrivers.
    for i in range(5):
        x=-1.20+i*0.16
        tube(f"PN_Tool_File_{i+1:02d}",[(x,0.05,1.115),(x+0.07,0.42,1.115)],0.012,m["steel"],col)
        cylinder(f"PN_Tool_FileHandle_{i+1:02d}",(x-0.015,-0.02,1.115),0.025,0.16,m["wood"],col,16,rotation=(math.pi/2,0,0))
    for i,x in enumerate((-0.95,-0.72),1):
        tube(f"PN_Tool_Pliers_{i:02d}_L",[(x,0.18,1.12),(x-0.07,0.43,1.12)],0.014,m["steel"],col)
        tube(f"PN_Tool_Pliers_{i:02d}_R",[(x+0.04,0.18,1.12),(x+0.11,0.43,1.12)],0.014,m["steel"],col)
    # Center-front measuring tools leave the hero plinth unobstructed.
    box("PN_Tool_MetalRule",(0,-0.02,1.105),(0.72,0.045,0.012),m["steel"],col,0.002)
    tube("PN_Tool_Caliper",[(0.55,0.03,1.12),(0.78,0.28,1.12),(0.72,0.36,1.12)],0.012,m["steel"],col)
    for i,x in enumerate((0.90,1.05,1.20),1):
        cylinder(f"PN_Tool_Screwdriver_{i:02d}",(x,0.12,1.12),0.018,0.34,m["brass"],col,16,rotation=(math.pi/2,0,0))
    # Component trays and acetate offcuts.
    for i,x in enumerate((1.35,2.05),1):
        box(f"PN_Tray_Components_{i:02d}",(x,0.10,1.125),(0.42,0.28,0.06),m["brass"],col,0.025)
        for j in range(7):
            cylinder(f"PN_Component_{i:02d}_{j+1:02d}",(x-0.14+(j%4)*0.09,0.04+(j//4)*0.10,1.17),0.018,0.012,m["steel"],col,12)
    for i in range(5):
        off=box(f"PN_Acetate_Offcut_{i+1:02d}",(-0.35+i*0.11,0.12+i*0.015,1.115),(0.18,0.08,0.018),m["acetate_sheet"],col,0.008)
        off.rotation_euler[2]=math.radians(-18+i*9)
    box("PN_Tool_SandingBlock",(0.72,0.42,1.16),(0.22,0.12,0.12),m["rubber"],col,0.018)
    cloth=box("PN_Tool_WorkCloth",(-0.34,0.62,1.12),(0.38,0.22,0.025),m["cloth"],col,0.015)
    cloth.rotation_euler[2]=math.radians(8)
    for i,x in enumerate((2.48,2.72,2.96),1):
        cylinder(f"PN_Container_{i:02d}",(x,0.20,1.24),0.055,0.28,m["glass"],col,20)
        cylinder(f"PN_ContainerCap_{i:02d}",(x,0.20,1.39),0.058,0.035,m["brass"],col,20)


def task_lamp(m,col,light_col):
    root=bpy.data.objects.new("PN_TaskLamp_Root",None); root.location=(-1.36,0.72,1.09); col.objects.link(root)
    cylinder("PN_TaskLamp_Base",(-1.36,0.72,1.15),0.18,0.10,m["steel"],col,28,parent=root)
    tube("PN_TaskLamp_ArmLower",[(-1.36,0.72,1.20),(-1.50,0.62,1.70)],0.025,m["steel"],col,parent=root)
    tube("PN_TaskLamp_ArmUpper",[(-1.50,0.62,1.70),(-1.28,0.48,1.96)],0.025,m["steel"],col,parent=root)
    bpy.ops.mesh.primitive_cone_add(vertices=32,radius1=0.18,radius2=0.08,depth=0.24,location=(-1.22,0.43,1.92),rotation=(math.pi/2,0,0))
    shade=bpy.context.object; shade.name="PN_TaskLamp_Shade"; shade.data.materials.append(m["steel"]); move(shade,col); shade.parent=root; shade.matrix_parent_inverse=root.matrix_world.inverted()
    data=bpy.data.lights.new("PN_TaskLamp_Practical_Data","POINT"); data.energy=22; data.color=(1.0,0.72,0.45); data.shadow_soft_size=0.28
    light=bpy.data.objects.new("PN_TaskLamp_Practical",data); light.location=(-1.18,0.30,1.82); light_col.objects.link(light)


def add_camera(name,loc,target,lens,col):
    bpy.ops.object.camera_add(location=loc)
    cam=bpy.context.object; cam.name=name; cam.data.name=name+"_Data"; cam.data.lens=lens
    cam.rotation_euler=(Vector(target)-cam.location).to_track_quat("-Z","Y").to_euler()
    move(cam,col)
    return cam


def render(scene,cam,path):
    scene.camera=cam; scene.render.filepath=str(path); bpy.ops.render.render(write_still=True)


def comparison(render_path):
    import numpy as np
    a=bpy.data.images.load(str(TARGET_PATH),check_existing=False); b=bpy.data.images.load(str(render_path),check_existing=False)
    a.scale(1536,1024); b.scale(1536,1024)
    pa=np.empty(1536*1024*4,dtype=np.float32); pb=np.empty_like(pa)
    a.pixels.foreach_get(pa); b.pixels.foreach_get(pb)
    canvas=np.concatenate((pa.reshape(1024,1536,4),pb.reshape(1024,1536,4)),axis=1)
    out=bpy.data.images.new("PN_Camera_Comparison_Props",3072,1024,alpha=True)
    out.pixels.foreach_set(canvas.ravel()); out.filepath_raw=str(COMPARISON_RENDER); out.file_format="PNG"; out.save()


def stats(cols):
    for name,col in cols.items():
        meshes=[o for o in col.all_objects if o.type=="MESH"]
        polys=sum(len(o.data.polygons) for o in meshes)
        tris=sum(max(1,len(p.vertices)-2) for o in meshes for p in o.data.polygons)
        curves=sum(o.type=="CURVE" for o in col.all_objects)
        est=tris*3*40/(1024*1024)*0.28
        print(f"PN_PROP_STATS {name} objects={len(col.all_objects)} meshes={len(meshes)} curves={curves} polygons={polys} triangles_mesh_only={tris} estimated_GLBGzip_MB={est:.3f}")


def main():
    RENDER_DIR.mkdir(parents=True,exist_ok=True)
    remove_old_pass()
    scene=bpy.context.scene
    desktop=bpy.data.objects["PN_Camera_Desktop"]
    approved=(desktop.location.copy(),desktop.rotation_euler.copy(),desktop.data.lens)
    anchors=sorted(o.name for o in bpy.data.objects if o.name.startswith("PN_LizardPath_Anchor_"))
    assert len(anchors)==8

    eyewear_col=collection("PN_Eyewear_Products")
    machine_col=collection("PN_Workshop_Machinery")
    tools_col=collection("PN_Hand_Tools")
    turntable_col=collection("PN_Turntable")
    staging_col=collection("PN_Product_Staging")
    cameras_col=collection("PN_Props_Cameras")
    light_col=collection("PN_Props_Lighting")
    m=create_materials()
    refine_approved_wood()
    roots=stage_eyewear(m,eyewear_col,staging_col)
    editorial_plates_and_shelf_lights(m,staging_col,light_col)
    drill_press(m,machine_col); buffer(m,machine_col); sander(m,machine_col); vise_and_heater(m,machine_col); machinery_details(m,machine_col)
    turntable(m,turntable_col); hand_tools(m,tools_col); task_lamp(m,tools_col,light_col)

    scene.render.resolution_x=1536; scene.render.resolution_y=1024; scene.render.resolution_percentage=100
    scene.view_settings.look="AgX - Medium High Contrast"
    # Recover exterior color and hold whites while preserving the approved direction.
    if "PN_Light_Window_Key_Data" in bpy.data.lights: bpy.data.lights["PN_Light_Window_Key_Data"].energy=440
    if "PN_Light_Exterior_Daylight_Data" in bpy.data.lights: bpy.data.lights["PN_Light_Exterior_Daylight_Data"].energy=570
    if "PN_Light_Bench_Bounce_Data" in bpy.data.lights: bpy.data.lights["PN_Light_Bench_Bounce_Data"].energy=340
    render(scene,desktop,MAIN_RENDER); comparison(MAIN_RENDER)
    bench=add_camera("PN_Camera_Props_Bench",(0,-6.8,1.72),(0,0.50,1.38),59,cameras_col)
    left=add_camera("PN_Camera_Props_Left",(-2.65,-5.2,2.38),(-2.65,1.05,2.38),72,cameras_col)
    right=add_camera("PN_Camera_Props_Right",(2.65,-5.2,2.38),(2.65,1.05,2.38),72,cameras_col)
    hero=add_camera("PN_Camera_Props_Hero",(0,-3.8,1.54),(0,0.35,1.34),78,cameras_col)
    record=add_camera("PN_Camera_Props_Turntable",(-3.30,-3.3,1.68),(-3.30,0.58,1.31),76,cameras_col)
    machine_left=add_camera("PN_Camera_Machinery_Left",(-2.05,-4.5,1.72),(-2.05,0.60,1.42),74,cameras_col)
    machine_right=add_camera("PN_Camera_Machinery_Right",(2.30,-4.8,1.82),(2.30,0.60,1.55),70,cameras_col)
    diagnostic=add_camera("PN_Camera_MaterialsDiagnostic",(0,-7.4,2.18),(0,0.55,1.72),64,cameras_col)
    render(scene,bench,BENCH_RENDER); render(scene,left,LEFT_RENDER); render(scene,right,RIGHT_RENDER)
    render(scene,hero,HERO_RENDER); render(scene,record,TURNTABLE_RENDER)
    render(scene,machine_left,MACHINE_LEFT_RENDER); render(scene,machine_right,MACHINE_RIGHT_RENDER)
    render(scene,diagnostic,DIAGNOSTIC_RENDER)

    desktop.location=approved[0]; desktop.rotation_euler=approved[1]; desktop.data.lens=approved[2]; scene.camera=desktop
    assert tuple(round(v,3) for v in desktop.location)==(0.0,-11.15,2.52) and desktop.data.lens==52
    eyewear_roots=sorted(o.name for o in bpy.data.objects if o.name.startswith("PN_Eyewear_") and o.type=="EMPTY")
    assert eyewear_roots==[f"PN_Eyewear_{i:02d}" for i in range(1,10)]
    # All machinery mesh bounds must sit on or above the approved counter surface.
    mins=[]
    for o in machine_col.all_objects:
        if o.type=="MESH":
            mins.append((o.name,min((o.matrix_world@Vector(c)).z for c in o.bound_box)))
    assert all(z>=COUNTER_TOP_Z-0.012 for _,z in mins),[v for v in mins if v[1]<COUNTER_TOP_Z-0.012]
    assert sorted(o.name for o in bpy.data.objects if o.name.startswith("PN_LizardPath_Anchor_"))==anchors
    stats({"eyewear":eyewear_col,"machinery":machine_col,"hand_tools":tools_col,"turntable":turntable_col,"staging":staging_col})
    print("PN_EYEWEAR_VALIDATION exactly=9 distribution=4-1-4 visible_roots="+",".join(eyewear_roots))
    print(f"PN_MACHINERY_VALIDATION all_on_counter=True minimum_z={min(z for _,z in mins):.3f} counter_top={COUNTER_TOP_Z:.3f}")
    print("PN_EXTERNAL_ASSETS none license=original_procedural_geometry")
    bpy.ops.wm.save_as_mainfile(filepath=str(BLEND_PATH))
    print(f"Created: {BLEND_PATH}")
    for p in (MAIN_RENDER,BENCH_RENDER,LEFT_RENDER,RIGHT_RENDER,HERO_RENDER,TURNTABLE_RENDER,
              MACHINE_LEFT_RENDER,MACHINE_RIGHT_RENDER,DIAGNOSTIC_RENDER,COMPARISON_RENDER): print(f"Created: {p}")


if __name__=="__main__":
    main()
